services:
  mlops-dev:
    container_name: unsw-mlops-dev
    image: unsw-mlops-dev
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "8888:8888"
    volumes:
      - .:/workspace/UNSW-NB15_mlops
    gpus: all
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/lib/wsl/lib:/usr/local/lib/python3.11/dist-packages/nvidia/cudnn/lib
    restart: unless-stopped
    command: >
      jupyter lab --ip=0.0.0.0 --no-browser --allow-root
      --ServerApp.token='' --ServerApp.password=''

