apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ids

resources:
  - ../../base
  - ids-api-hpa.yaml

patches:
  # Override ids-api with ECR image
  - target:
      kind: Deployment
      name: ids-api
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ids-api
      spec:
        template:
          spec:
            containers:
            - name: api
              image: 002232587129.dkr.ecr.af-south-1.amazonaws.com/unsw-nb15-mlops-api:latest
              imagePullPolicy: IfNotPresent

  # ids-api CPU/mem limits
  - target:
      kind: Deployment
      name: ids-api
    path: ids-api-resources.yaml

  # Override dash-ui with ECR image, LoadBalancer service, and production probe/resource settings
  - path: dash-ui.yaml
